const { SlashCommandBuilder } = require('@discordjs/builders');
const { MessageEmbed } = require('discord.js');
const axios = require('axios');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('analyzeexploit')
        .setDescription('Upload a .txt or .lua file for exploit analysis and suggestions.')
        .addAttachmentOption(option =>
            option.setName('file')
                .setDescription('The .txt or .lua file to analyze')
                .setRequired(true)
        ),
    async execute(interaction) {
        const file = interaction.options.getAttachment('file');

        // Fetch the file content
        const fileResponse = await axios.get(file.url);
        const fileContent = fileResponse.data;

        // Create a prompt for the AI to analyze the code for exploits
        const prompt = `Analyze the following code for potential exploits or improvements. Content: ${fileContent}`;

        const processingEmbed = new MessageEmbed()
            .setColor('#0092e0')
            .setTitle('Exploit Analysis in Progress')
            .setDescription(`Analyzing the file: "${file.name}" for exploits...`)
            .setTimestamp();

        await interaction.reply({ embeds: [processingEmbed] });

        try {
            const response = await axios.post(
                `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=${process.env.GOOGLE_API_KEY}`,
                {
                    contents: [
                        {
                            parts: [
                                {
                                    text: prompt
                                }
                            ]
                        }
                    ]
                },
                {
                    headers: {
                        'Content-Type': 'application/json'
                    }
                }
            );

            const aiResponse = response.data.candidates[0].content.parts[0].text;

            const resultEmbed = new MessageEmbed()
                .setColor('#00FF00')
                .setTitle('Exploit Suggestions')
                .setDescription(`Here are the suggestions for "${file.name}":`)
                .addField('Suggestions', `\`\`\`txt\n${aiResponse}\n\`\`\``)
                .setFooter('Suggestions generated by AI.')
                .setTimestamp();

            await interaction.followUp({ embeds: [resultEmbed] });
        } catch (error) {
            console.error('Error interacting with AI API:', error);
            return interaction.followUp('Sorry, I couldn\'t generate suggestions at the moment.');
        }
    }
};
