const { SlashCommandBuilder } = require('@discordjs/builders');
const { MessageEmbed } = require('discord.js');
const axios = require('axios');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('improvefile')
        .setDescription('Upload a .txt or .lua file to receive improvement suggestions using AI.')
        .addAttachmentOption(option => 
            option.setName('file')
                .setDescription('The .txt or .lua file to be improved')
                .setRequired(true)
        )
        .addStringOption(option =>
            option.setName('improvement_type')
                .setDescription('Specify the type of improvement (e.g., "optimize", "debug", "enhance")')
                .setRequired(false)
                .addChoices(
                    { name: 'Optimize', value: 'optimize' },
                    { name: 'Debug', value: 'debug' },
                    { name: 'Enhance', value: 'enhance' }
                )
        ),
    async execute(interaction) {
        const file = interaction.options.getAttachment('file');
        const improvementType = interaction.options.getString('improvement_type') || 'enhance';

        // Fetch the file content
        const fileResponse = await axios.get(file.url);
        const fileContent = fileResponse.data;

        // Create a prompt for the AI
        const prompt = `Analyze the following ${file.name.endsWith('.lua') ? 'Lua' : 'text'} code and suggest improvements. The improvement type is: ${improvementType}. Content: ${fileContent}`;

        const processingEmbed = new MessageEmbed()
            .setColor('#0092e0')
            .setTitle('Improvement Analysis in Progress')
            .setDescription(`Analyzing the file: "${file.name}" with improvement type: "${improvementType}"`)
            .setTimestamp();

        await interaction.reply({ embeds: [processingEmbed] });

        try {
            const response = await axios.post(
                `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=${process.env.GOOGLE_API_KEY}`,
                {
                    contents: [
                        {
                            parts: [
                                {
                                    text: prompt
                                }
                            ]
                        }
                    ]
                },
                {
                    headers: {
                        'Content-Type': 'application/json'
                    }
                }
            );

            const aiResponse = response.data.candidates[0].content.parts[0].text;

            const resultEmbed = new MessageEmbed()
                .setColor('#00FF00')
                .setTitle('Improvement Suggestions')
                .setDescription(`Here are the suggested improvements for "${file.name}":`)
                .addField('Suggestions', `\`\`\`txt\n${aiResponse}\n\`\`\``)
                .setFooter('Suggestions generated by AI.')
                .setTimestamp();

            await interaction.followUp({ embeds: [resultEmbed] });
        } catch (error) {
            console.error('Error interacting with AI API:', error);
            return interaction.followUp('Sorry, I couldn\'t generate suggestions at the moment.');
        }
    }
};
