const { SlashCommandBuilder } = require('@discordjs/builders');
const { MessageEmbed } = require('discord.js');
const axios = require('axios');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('snippet')
        .setDescription('Generate a code snippet using AI.')
        .addStringOption(option =>
            option.setName('language')
                .setDescription('The programming language for the snippet')
                .setRequired(true)
                .addChoices(
                    { name: 'Java', value: 'java' },
                    { name: 'JavaScript', value: 'javascript' },
                    { name: 'Python', value: 'python' },
                    { name: 'C++', value: 'cpp' },
                    { name: 'Go', value: 'go' },
                    { name: 'Ruby', value: 'ruby' }
                )
        )
        .addStringOption(option =>
            option.setName('description')
                .setDescription('Description of the snippet (e.g., "Create a function to reverse a string")')
                .setRequired(true)
        ),
    async execute(interaction) {
        const language = interaction.options.getString('language');
        const description = interaction.options.getString('description');

        // Prepare the prompt for the AI
        const prompt = `Create a ${language} code snippet that accomplishes the following task: ${description}`;

        // Send an initial message with an embed indicating processing
        const processingEmbed = new MessageEmbed()
            .setColor('#00FF00') // Green color
            .setTitle('Snippet Generation')
            .setDescription(`Generating a ${language} code snippet for: "${description}"`)
            .setTimestamp();

        await interaction.reply({ embeds: [processingEmbed] });

        try {
            // Make a request to the AI API
            const response = await axios.post(
                `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=${process.env.GOOGLE_API_KEY}`,
                {
                    contents: [
                        {
                            parts: [
                                {
                                    text: prompt
                                }
                            ]
                        }
                    ]
                },
                {
                    headers: {
                        'Content-Type': 'application/json'
                    }
                }
            );

            const aiResponse = response.data.candidates[0].content.parts[0].text;

            // Embed to show the generated snippet
            const resultEmbed = new MessageEmbed()
                .setColor('#00FF00') // Green color
                .setTitle(`${language.charAt(0).toUpperCase() + language.slice(1)} Code Snippet`)
                .setDescription(`Here is the generated code snippet for "${description}":`)
                .addField('Snippet', `\`\`\`${language}\n${aiResponse}\n\`\`\``)
                .setFooter('Snippet generated by AI.')
                .setTimestamp();

            interaction.followUp({ embeds: [resultEmbed] });
        } catch (error) {
            console.error('Error interacting with AI API:', error);
            return interaction.followUp('Sorry, I couldn\'t generate a snippet at the moment.');
        }
    }
};
